# Generated by Django 4.2.20 on 2025-08-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='address',
            field=models.TextField(default='Unknow'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='contact_no',
            field=models.CharField(default='00000000', max_length=20),
            preserve_default=False,
        ),
    ]
