# Generated by Django 4.2.20 on 2025-08-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_facultyprofile_address_facultyprofile_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='exam_type',
            field=models.CharField(default='NUll', max_length=100),
            preserve_default=False,
        ),
    ]
