# Generated by Django 4.2.20 on 2025-09-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_marks_exam_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('monday', models.CharField(blank=True, max_length=100, null=True)),
                ('tuesday', models.CharField(blank=True, max_length=100, null=True)),
                ('wednesday', models.CharField(blank=True, max_length=100, null=True)),
                ('thursday', models.CharField(blank=True, max_length=100, null=True)),
                ('friday', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
